import shark from "../assets/icon/shark_icon.svg";

export const fishdata = [
  {
    id: 1,
    color: "#D9D9D9",
    text: "빙어",
    count: 3,
    status: "common",
    image: shark,
  },
  {
    id: 2,
    color: "tomato",
    text: "송어",
    count: 2,
    status: "common",
    image: shark,
  },
  {
    id: 3,
    color: "tomato",
    text: "복어",
    count: 1,
    status: "common",
    image: shark,
  },
  {
    id: 4,
    color: "tomato",
    text: "비단잉어",
    count: 1,
    status: "rare",
    image: shark,
  },
  {
    id: 5,
    color: "tomato",
    text: "베타",
    count: 1,
    status: "rare",
    image: shark,
  },
  {
    id: 6,
    color: "tomato",
    text: "갈치",
    count: 1,
    status: "rare",
    image: shark,
  },
  {
    id: 7,
    color: "tomato",
    text: "황금 빙어",
    count: 1,
    status: "legendary",
    image: shark,
  },
  {
    id: 8,
    color: "tomato",
    text: "상어",
    count: 1,
    status: "legendary",
    image: shark,
  },
  {
    id: 9,
    color: "tomato",
    text: "붕어빵",
    count: 1,
    status: "funny",
    image: shark,
  },
];
